version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  consumer:
    build:
      context: .
    depends_on:
      - rabbitmq
    command: ["/bin/bash", "-c", ". venv/bin/activate && python consumer.py"]
  producer:
    build:
      context: .
    depends_on:
      - rabbitmq
    command: ["/bin/bash", "-c", ". venv/bin/activate && python producer.py"]
