version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "5672:5672"
      - "15672:15672"
      - "8080:80"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    command: ["/bin/bash", "-c", "rabbitmq-server & sleep 15 && . venv/bin/activate && python producer.py"]
  consumer:
    build:
      context: .
    depends_on:
      - app
    command: ["/bin/bash", "-c", "sleep 10 && . venv/bin/activate && python consumer.py"]
