version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  producer:
    build:
      context: .
      dockerfile: Dockerfile-producer
    depends_on:
      - rabbitmq
  consumer:
    build:
      context: .
      dockerfile: Dockerfile-consumer
    depends_on:
      - rabbitmq
